// Code generated by protoc-gen-go.
// source: Bool.proto
// DO NOT EDIT!

/*
Package protocol_v1 is a generated protocol buffer package.

It is generated from these files:
	Bool.proto
	Bytes.proto
	CallMember.proto
	Close.proto
	Envelope.proto
	Error.proto
	Handshake.proto

It has these top-level messages:
	Bool
	Bytes
	CallMember
	Close
	Envelope
	Error
	Handshake
*/
package protocol_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bool struct {
	Value bool `protobuf:"varint,1,opt,name=Value" json:"Value,omitempty"`
}

func (m *Bool) Reset()                    { *m = Bool{} }
func (m *Bool) String() string            { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()               {}
func (*Bool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*Bool)(nil), "protocol.v1.Bool")
}

func init() { proto.RegisterFile("Bool.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x72, 0xca, 0xcf, 0xcf,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x53, 0xc9, 0xf9, 0x39, 0x7a, 0x65, 0x86,
	0x4a, 0x32, 0x5c, 0x2c, 0x20, 0x29, 0x21, 0x11, 0x2e, 0xd6, 0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x08, 0x27, 0x89, 0x0d, 0xac, 0xd4, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x61, 0x9e, 0xec, 0xc8, 0x3f, 0x00, 0x00, 0x00,
}
