// Code generated by protoc-gen-go.
// source: Close.proto
// DO NOT EDIT!

package protocol_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Close struct {
}

func (m *Close) Reset()                    { *m = Close{} }
func (m *Close) String() string            { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()               {}
func (*Close) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func init() {
	proto.RegisterType((*Close)(nil), "protocol.v1.Close")
}

func init() { proto.RegisterFile("Close.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 57 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x76, 0xce, 0xc9, 0x2f,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x53, 0xc9, 0xf9, 0x39, 0x7a, 0x65,
	0x86, 0x4a, 0xec, 0x5c, 0xac, 0x60, 0xb9, 0x24, 0x36, 0xb0, 0xa8, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0x03, 0x6c, 0xef, 0x2b, 0x00, 0x00, 0x00,
}
